# Generated by Django 5.0.6 on 2024-06-28 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 28, 17, 26, 18, 343225)),
        ),
    ]
