# Generated by Django 5.0.6 on 2024-06-28 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_comments_item_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='itemId',
        ),
        migrations.RemoveField(
            model_name='location',
            name='locationId',
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 28, 18, 13, 58, 110575)),
        ),
    ]
